services:
  db:
    image: postgres:16
    container_name: analytics_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: analytics
      POSTGRES_PASSWORD: analytics_pass
      POSTGRES_DB: analytics
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
